import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  staticPageGenerationTimeout: 180,
  experimental: {
    cpus: 4,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
  },
  async redirects() {
    return [
      { source: "/mental-health/mood-disorders/major-depressive-disorder", destination: "/mental-health/mood-disorders/depression/major-depressive-disorder", permanent: true },
      { source: "/mental-health/therapy/orange-county-ca/orange-county-anxiety-treatment-center", destination: "/mental-health/anxiety-disorders/orange-county-ca", permanent: true },
      { source: "/mental-health/therapy/los-angeles-ca/claremont", destination: "/mental-health/therapy/outpatient/los-angeles-ca", permanent: true },
      { source: "/schizoaffective-disorder", destination: "/mental-health/psychotic-disorders/schizophrenia/schizoaffective-disorder", permanent: true },
      { source: "/staff/erica-chavez-clinical-director-bio", destination: "/staff", permanent: true },
      { source: "/staff/paula-bouza-author-bio", destination: "/staff", permanent: true },
      { source: "/staff/neil-appleby-author-bio", destination: "/staff", permanent: true },
      { source: "/staff/maxwell-kaminski-operations-manager", destination: "/staff", permanent: true },
      { source: "/staff/luis-fraire-therapist", destination: "/staff", permanent: true },
      { source: "/mental-health-treatment/cognitive-behavioral-therapy-cbt", destination: "/mental-health/therapy/cognitive-behavioral-therapy-cbt", permanent: true },
      { source: "/mental-health-treatment/dbt", destination: "/mental-health/therapy/dbt", permanent: true },
      { source: "/holistic-mental-health-treatment", destination: "/mental-health/holistic-mental-health-treatment", permanent: true },
      { source: "/mental-health-treatment/emdr", destination: "/mental-health/therapy/emdr", permanent: true },
      { source: "/mental-health-treatment/seeking-safety", destination: "/mental-health/therapy/seeking-safety", permanent: true },
      { source: "/mental-health-treatment/motivational-interviewing", destination: "/mental-health/therapy/motivational-interviewing", permanent: true },
      { source: "/mental-health-treatment/medication-management", destination: "/mental-health/therapy/medication-management", permanent: true },
      { source: "/mental-health-disorders", destination: "/mental-health", permanent: true },
      { source: "/mental-health-disorders/depression", destination: "/mental-health/mood-disorders/depression", permanent: true },
      { source: "/mental-health-disorders/anxiety-disorders", destination: "/mental-health/anxiety-disorders", permanent: true },
      { source: "/mental-health-disorders/schizophrenia", destination: "/mental-health/psychotic-disorders/schizophrenia", permanent: true },
      { source: "/mental-health-disorders/mood-disorders", destination: "/mental-health/mood-disorders", permanent: true },
      { source: "/mental-health-disorders/ocd", destination: "/mental-health/anxiety-disorders/obsessive-compulsive-disorder", permanent: true },
      { source: "/mental-health-disorders/eating-disorders", destination: "/mental-health/eating-disorders", permanent: true },
      { source: "/mental-health-disorders/adhd", destination: "/mental-health/neurodevelopment-disorder/adhd", permanent: true },
      { source: "/does-depression-go-away", destination: "/mental-health/mood-disorders/depression/does-depression-go-away", permanent: true },
      { source: "/mental-health-disorders/depression/major-depressive-disorder", destination: "/mental-health/mood-disorders/depression/major-depressive-disorder", permanent: true },
      { source: "/intrusive-vs-impulsive-thoughts", destination: "/mental-health/vs/intrusive-vs-impulsive-thoughts", permanent: true },
      { source: "/mental-health-advocacy", destination: "/mental-health/mental-health-advocacy", permanent: true },
      { source: "/passive-suicidal-ideation", destination: "/mental-health/mood-disorders/depression/passive-suicidal-ideation", permanent: true },
      { source: "/adhd-paralysis", destination: "/mental-health/neurodevelopment-disorder/adhd/adhd-paralysis", permanent: true },
      { source: "/passive-suicidal-ideation-adhd", destination: "/mental-health/neurodevelopment-disorder/adhd/passive-suicidal-ideation-adhd", permanent: true },
      { source: "/mental-health/therapy/california/orange-county/tustin", destination: "/mental-health/therapy/tustin-ca", permanent: true },
      { source: "/is-schizophrenia-genetic", destination: "/mental-health/psychotic-disorders/schizophrenia/is-schizophrenia-genetic", permanent: true },
      { source: "/orange-county-anxiety-treatment-center", destination: "/mental-health/anxiety-disorders/orange-county-ca", permanent: true },
      { source: "/mental-health/mood-disorders/depression/%20", destination: "/mental-health/mood-disorders/depression", permanent: true },
      { source: "/mental-health/anxiety-disorders/%20", destination: "/mental-health/anxiety-disorders", permanent: true },
      { source: "/mental-health/personality-disorders/borderline-personality-disorder/%20", destination: "/mental-health/personality-disorders/borderline-personality-disorder", permanent: true },
      { source: "/mental-health/anxiety-disorders/obsessive-compulsive-disorder/%20", destination: "/mental-health/anxiety-disorders/obsessive-compulsive-disorder", permanent: true },
      { source: "/mental-health/eating-disorders/%20", destination: "/mental-health/eating-disorders", permanent: true },
      { source: "/mental-health/psychotic-disorders/schizophrenia/%20", destination: "/mental-health/psychotic-disorders/schizophrenia", permanent: true },
      { source: "/mental-health/neurodevelopment-disorder/adhd/%20", destination: "/mental-health/neurodevelopment-disorder/adhd", permanent: true },
      { source: "/mental-health/grief-counseling/%20", destination: "/mental-health/grief-counseling", permanent: true },
      { source: "/mental-health/anxiety-disorders/inpatient-anxiety-treatment/%20%20%20", destination: "/mental-health/anxiety-disorders/inpatient-anxiety-treatment", permanent: true },
      { source: "/mental-health-disorders/generalized-anxiety-disorder", destination: "/mental-health/anxiety-disorders/generalized-anxiety-disorder", permanent: true },
      { source: "/orange-county-depression-treatment", destination: "/mental-health/mood-disorders/depression", permanent: true },
      { source: "/how-to-help-someone-with-depression", destination: "/mental-health/mood-disorders/depression/how-to-help-someone-with-depression", permanent: true },
      { source: "/faq", destination: "/mental-health/faq", permanent: true },
      { source: "/why-do-people-go-to-therapy", destination: "/mental-health/therapy/why-do-people-go-to-therapy", permanent: true },
      { source: "/adhd-and-depression", destination: "/mental-health/mood-disorders/depression/adhd-and-depression", permanent: true },
      { source: "/anxiety-attack-panic-attack", destination: "/mental-health/vs/anxiety-attack-panic-attack", permanent: true },
      { source: "/depression-in-women", destination: "/mental-health/mood-disorders/depression/depression-in-women", permanent: true },
      { source: "/cptsd-vs-ptsd", destination: "/mental-health/vs/cptsd-vs-ptsd", permanent: true },
      { source: "/is-ocd-genetic", destination: "/mental-health/anxiety-disorders/obsessive-compulsive-disorder/is-ocd-genetic", permanent: true },
      { source: "/anxiety-and-sleep", destination: "/mental-health/anxiety-disorders/anxiety-and-sleep", permanent: true },
      { source: "/schizophrenia-support-groups", destination: "/mental-health/psychotic-disorders/schizophrenia/schizophrenia-support-groups", permanent: true },
      { source: "/community-and-mental-health", destination: "/mental-health/community-and-mental-health", permanent: true },
      { source: "/why-do-i-wake-up-anxious", destination: "/mental-health/anxiety-disorders/why-do-i-wake-up-anxious", permanent: true },
      { source: "/what-is-inpatient-mental-health", destination: "/mental-health/therapy/what-is-inpatient-mental-health", permanent: true },
      { source: "/music-and-mental-health", destination: "/mental-health/music-and-mental-health", permanent: true },
      { source: "/mental-health-disorders/borderline-personality-disorder", destination: "/mental-health/personality-disorders/borderline-personality-disorder", permanent: true },
      { source: "/mindfulness-exercises", destination: "/mental-health/mood-disorders/depression/mindfulness-exercises", permanent: true },
      { source: "/seasonal-depression", destination: "/mental-health/mood-disorders/seasonal-affective-disorder", permanent: true },
      { source: "/drug-rehab/addiction-therapy", destination: "/mental-health/therapy/addiction-therapists-counselors", permanent: true },
      { source: "/drug-rehab/cognitive-behavioral-therapy", destination: "/mental-health/therapy/cognitive-behavioral-therapy-cbt", permanent: true },
      { source: "/mental-health-disorders/social-anxiety-disorder", destination: "/mental-health/anxiety-disorders/social-anxiety-disorder", permanent: true },
      { source: "/bad-mental-health-day", destination: "/mental-health/bad-mental-health-day", permanent: true },
      { source: "/dynamic-interpersonal-therapy", destination: "/mental-health/therapy/dynamic-interpersonal-therapy", permanent: true },
      { source: "/5-stages-psychosis", destination: "/mental-health/psychotic-disorders/5-stages-psychosis", permanent: true },
    ];
  },
}

export default nextConfig
